In [3]:
import pandas as pd
df = pd.read_csv('claims_main.csv')

In [5]:
df.shape

(120000, 25)

In [6]:
payers_df = df[['payer_type']].drop_duplicates()
payers_df

           payer_type
0      Commercial_PPO
1        Medicare_FFS
2      Commercial_EPO
4    Medicaid_Managed
5  Medicare_Advantage
9      Commercial_HMO

In [11]:
payers_df['payer_id'] = range(1, len(payers_df) + 1)

In [12]:
payers_df

           payer_type  payer_id
0      Commercial_PPO         1
1        Medicare_FFS         2
2      Commercial_EPO         3
4    Medicaid_Managed         4
5  Medicare_Advantage         5
9      Commercial_HMO         6

In [13]:
denial_reasons_df = df[['denial_reason_code', 'denial_category']].drop_duplicates()
denial_reasons_df

    denial_reason_code    denial_category
0                 CO-4       coding_error
1                CO-97          duplicate
2                 CO-4           bundling
3                  NaN                NaN
4                CO-16       auth_missing
5                CO-11  medical_necessity
6                N-130       auth_missing
8               CO-109  medical_necessity
21               CO-50  medical_necessity
32               CO-16       coding_error
42               PR-27        eligibility
51               CO-97       coding_error
52               OA-18          duplicate
55               CO-11       coding_error
72               CO-22        eligibility
79               CO-18          duplicate
88              PR-204       auth_missing
98              CO-119  medical_necessity
124             CO-109        eligibility
137              CO-29      timely_filing
142              CO-97           bundling
467              OA-23           bundling

In [14]:
denial_reasons_df['denial_id'] = range(1, len(denial_reasons_df) + 1)
denial_reasons_df

    denial_reason_code    denial_category  denial_id
0                 CO-4       coding_error          1
1                CO-97          duplicate          2
2                 CO-4           bundling          3
3                  NaN                NaN          4
4                CO-16       auth_missing          5
5                CO-11  medical_necessity          6
6                N-130       auth_missing          7
8               CO-109  medical_necessity          8
21               CO-50  medical_necessity          9
32               CO-16       coding_error         10
42               PR-27        eligibility         11
51               CO-97       coding_error         12
52               OA-18          duplicate         13
55               CO-11       coding_error         14
72               CO-22        eligibility         15
79               CO-18          duplicate         16
88              PR-204       auth_missing         17
98              CO-119  medical_necessity         18
124             CO-109        eligibility         19
137              CO-29      timely_filing         20
142              CO-97           bundling         21
467              OA-23           bundling         22

In [20]:
claims_df = df.merge(payers_df, on='payer_type')
claims_df = claims_df.merge(denial_reasons_df, on=['denial_reason_code', 'denial_category'])
claims_df.shape

(120000, 27)

In [21]:
import sqlite3
conn = sqlite3.connect('claims.db')

In [22]:
claims_df.to_sql('claims', conn, if_exists='replace', index=False)

120000

In [23]:
payers_df.to_sql('payers', conn, if_exists='replace', index=False)

6

In [24]:
denial_reasons_df.to_sql('denial_reasons', conn, if_exists='replace', index=False)

22